### ISSUE TITLE
Using petal library with Phoenix 1.17.0-rc.0

### ISSUE THREAD

**Issue by saleyn** [petalframework/petal_components#108]
I've encountered this issue when trying to port a sample project to `Phoenix 1.17.0-rc.0`:

```
== Compilation error in file lib/my_web/live/page_live.ex ==
** (CompileError) lib/my_web/live/page_live.ex:33: function button/1 imported from both PetalComponents.Button and MyWeb.CoreComponents, call is ambiguous
    (phoenix_live_view 0.18.3) expanding macro: Phoenix.LiveView.HTMLEngine.inner_block/2
    lib/my_web/live/page_live.ex:142: MyWeb.PageLive.render/1
    (phoenix_live_view 0.18.3) expanding macro: Phoenix.Component.sigil_H/2
    lib/my_web/live/page_live.ex:33: MyWeb.PageLive.render/1
```

The `page_live.ex` was included as part of the `petal.build` template, and apparently there is a naming collision of the button component with the new CoreComponents generated by Phoenix 1.17.

What is the suggested solution?

**Comment by mplatts** [comment]
Hi @saleyn, yeah Phoenix 1.17 comes with a file called `core_components.ex` which defines some components, including their own version of a button. You could simply go in and delete or comment out the button function in there. 

Or you could pick and choose which Petal Components you want. Instead of `use PetalComponents` you can go:

```elixir
import PetalComponents.{
    Alert,
    Badge,
    Button,
    Container,
    Dropdown,
    Form,
    Loading,
    Typography,
    Avatar,
    Progress,
    Breadcrumbs,
    Pagination,
    Link,
    Modal,
    SlideOver,
    Tabs,
    Card,
    Table,
    Accordion
  }

  alias PetalComponents.HeroiconsV1
```

And omit Button if you'd prefer the Phoenix one.

The same thing will probably happen with modal.

Open to ideas about avoiding naming collisions. We could make it so you use a module - eg `<PC.button></PC.button>`, `<PC.container></PC.container>` etc.

**Comment by saleyn** [comment]
I think using a "PC" module prefix would avoid collisions with other components, and would be more portable for all projects.

**Comment by mplatts** [comment]
https://github.com/petalframework/petal_boilerplate now uses Phoenix 1.7. I'll leave this open as I still need to do proper instructions.

**Comment by mplatts** [comment]
Added some instructions to https://github.com/petalframework/petal_components/blob/main/UPGRADE_GUIDE.md
